version: "3.2"
services:
  scraper:
    build: 
      context: .
    image: maxgordeev88/scraper
    container_name: scraper
    ports:
      - "5000:5000"
    networks:
      - backend
    command: ["wait-for-it", "mysql:3306", "--timeout=240","--","scrapy", "crawl", "quotes"]

  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass 
      - MYSQL_DATABASE=my_db
    container_name: mysql-app
    command: ["--init-file=/tmp/mysql-init.sql", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./scraper/db_dir:/var/lib/mysql
      - ./scraper/mysql-init.sql:/tmp/mysql-init.sql
    ports:
      - "3306:3306"
    expose:
      - 3306  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend: